extends: ["https://unpkg.com/@stoplight/spectral-owasp-ruleset/dist/ruleset.mjs"]
rules:
  owasp:api2:2023-auth-insecure-schemes : off
  owasp:api2:2023-jwt-best-practices : off
  owasp:api2:2023-no-http-basic : off
  owasp:api4:2023-integer-limit : off
  owasp:api4:2023-rate-limit : off
  owasp:api4:2023-rate-limit-retry-after : off
  owasp:api4:2023-rate-limit-responses-429 : off
  owasp:api8:2023-define-cors-origin : off
  owasp:api8:2023-define-error-responses-500 : off
  owasp:api8:2023-define-error-responses-401 : error 
  owasp:api9:2023-inventory-access : off
  owasp:api9:2023-inventory-environment : off
