name: Execute Spectral with CAMARA ruleset
# A reusable action for validating PRs using tools configuration from branch indicated by input `configurations` variable
# CAMARA Project - Github Action 
# initial version

on:
  workflow_call:
    # For a workflow to be reusable, the values for on must include workflow_call
    inputs:
      configurations:
        description: The branch, tag, or commit to check out - containing tool configs to be used
        type: string
        required: false
        default: main
jobs:
  execute:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
      - name: Checkout linting config
        uses: actions/checkout@v4
        with:
          repository: rartych/tooling
          path: lint-config
          ref: ${{ inputs.configurations }}
          sparse-checkout: |
            linting/config/
          sparse-checkout-cone-mode: false
      - name: Copy specified folder to workspace root
        run: cp -RT ${{ github.workspace }}/lint-config/linting/config ${{ github.workspace }}
#      - name: Install Spectral
#        run: npm install -g @stoplight/spectral
      - name: Install Spectral CLI
        run: npm install -g @stoplight/spectral-cli
      - name: Install Spectral functions
        run: npm install -g @stoplight/spectral-functions
      - name: Run Spectral linting
        run: spectral lint code/API_definitions/*.yaml --verbose --ruleset ${{ github.workspace }}/.spectral.yaml
      - name: Install Spectral OWASP
        run: npm install -g @stoplight/spectral-owasp-ruleset@^2.0
#      - name: List contents of github.workspace
#        run: ls -la ${{ github.workspace }}
      - name: Run Spectral linting for OWASP
        run: spectral lint code/API_definitions/*.yaml --verbose --ruleset ${{ github.workspace }}/.spectral-owasp.yaml
        continue-on-error: true
        
